### ISSUE TITLE
2 factor auth

### ISSUE THREAD

**Issue by jo45** [eisbaw/google_shared_locations#1]
Hello.

Your code is very interesting and useful. The only problem I found is it can't authenticate when 2 factor auth is enabled on Google account.

Could you implement it?

**Comment by jo45** [comment]
Hello.

There seems to be an error when one user that share location on the Google account don't have data to provide:

ypeError: Cannot read property '1' of null
    at extractUserLocationData (/opt/google_shared_locations/main.js:507:34)
    at parseLocationData (/opt/google_shared_locations/main.js:485:7)
    at Request._callback (/opt/google_shared_locations/main.js:412:11)
    at Request.self.callback (/opt/google_shared_locations/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/opt/google_shared_locations/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/opt/google_shared_locations/node_modules/request/request.js:1085:12)
